
package bankproject;

import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Timer;
import javax.print.CancelablePrintJob;

/**
 * @author A.A. Yapan
 */
public class After_login extends javax.swing.JFrame {

    /**
     * Creates new form Client_homepage
     */
    private static String username;
    private static String password;
    
    public After_login(String x, String y) {
        initComponents();
        username = x;
        password = y;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Lambda_Loans = new javax.swing.JLabel();
        Saying = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        Underline = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(413, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(244, 169, 80));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 33), 2, true));

        jPanel2.setBackground(new java.awt.Color(22, 27, 33));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_hand_holding_dollar_120px_1.png"))); // NOI18N

        Lambda_Loans.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Lambda_Loans.setForeground(new java.awt.Color(244, 169, 80));
        Lambda_Loans.setText("LAMBDA LOANS");
        Lambda_Loans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lambda_LoansMouseClicked(evt);
            }
        });

        Saying.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        Saying.setForeground(new java.awt.Color(240, 240, 240));
        Saying.setText("OUGHT TO SECURE YOUR MONEY");

        loading.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        loading.setForeground(new java.awt.Color(244, 169, 80));
        loading.setText("   Press here to continue.");
        loading.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loadingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loadingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Logo)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Lambda_Loans, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(Saying, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(64, 64, 64)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Underline, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(Logo)
                .addGap(0, 0, 0)
                .addComponent(Lambda_Loans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Saying)
                .addGap(36, 36, 36)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Underline, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lambda_LoansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lambda_LoansMouseClicked

    }//GEN-LAST:event_Lambda_LoansMouseClicked

    
   
    Timer timer;
    int secStart = 1;
    Boolean clickable = true;
    
    private void loadingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadingMouseClicked
        //Underline.setVisible(false);
        if (clickable){
        clickable = false;
        loading.setText("");
        
        TimerTask task = new TimerTask(){
        String startStr = "      ."; //For loading
        public void run(){
            
            if((secStart >= 1) && (secStart != 28)){
                loading.setText(startStr);
                startStr = startStr+".";               
            }else if (secStart == 28){
                dispose();
                timer.cancel();
                cancel();
                                              
                Client_homepage CHomePage = new Client_homepage(username, password);
                CHomePage.setVisible(true);
                CHomePage.setLocationRelativeTo(null);
                
            }
            secStart++;
        }
        };
        
        timer = new Timer();
        timer.schedule(task, 100, 100);
        
        }  
    }//GEN-LAST:event_loadingMouseClicked

    private void loadingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadingMouseEntered
        // TODO add your handling code here:
        loading.setForeground(new java.awt.Color(240,240,240));
        
    }//GEN-LAST:event_loadingMouseEntered

    private void loadingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadingMouseExited
        // TODO add your handling code here:
        loading.setForeground(new java.awt.Color(244,169,80));
    }//GEN-LAST:event_loadingMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(After_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(After_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(After_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(After_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new After_login(username,password).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lambda_Loans;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Saying;
    private javax.swing.JSeparator Underline;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loading;
    // End of variables declaration//GEN-END:variables
}
