package bankproject;

import java.awt.Color;
import java.awt.Font;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 * @author Kkoli
 */
public class Card_window extends javax.swing.JFrame {

    /**
     * Creates new form Profile_window
     */
    
    private static String username;
    private static String password;
    public Card_window(String x, String y) {
        username = x;
        password = y;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Exit_button = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lambda = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Add_Debt = new javax.swing.JLabel();
        Pay_Debt = new javax.swing.JLabel();
        Check_Balance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 169, 80));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel2.setBackground(new java.awt.Color(22, 27, 33));

        Exit_button.setForeground(new java.awt.Color(240, 240, 240));
        Exit_button.setText("X");
        Exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_buttonMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_debit_card_125px.png"))); // NOI18N

        Lambda.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Lambda.setForeground(new java.awt.Color(244, 169, 80));
        Lambda.setText("LAMBDA");
        Lambda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LambdaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LambdaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LambdaMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(244, 169, 80));
        jLabel3.setText("Card");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(244, 169, 80));
        jLabel4.setText("Manage your");

        Add_Debt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add_Debt.setForeground(new java.awt.Color(244, 169, 80));
        Add_Debt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add_Debt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_plus_20px.png"))); // NOI18N
        Add_Debt.setText("Add Debt");
        Add_Debt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 169, 80), 5));
        Add_Debt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_DebtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_DebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_DebtMouseExited(evt);
            }
        });

        Pay_Debt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Pay_Debt.setForeground(new java.awt.Color(244, 169, 80));
        Pay_Debt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pay_Debt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_minus_20px_2.png"))); // NOI18N
        Pay_Debt.setText("Pay Debt");
        Pay_Debt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 169, 80), 5));
        Pay_Debt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pay_DebtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pay_DebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pay_DebtMouseExited(evt);
            }
        });

        Check_Balance.setBackground(new java.awt.Color(244, 169, 80));
        Check_Balance.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Check_Balance.setForeground(new java.awt.Color(244, 169, 80));
        Check_Balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Check_Balance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_debt_20px.png"))); // NOI18N
        Check_Balance.setText("\nCheck Balance");
        Check_Balance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 169, 80), 5));
        Check_Balance.setIconTextGap(1);
        Check_Balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check_BalanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Check_BalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Check_BalanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Check_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add_Debt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pay_Debt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Lambda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit_button)
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lambda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Debt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pay_Debt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_buttonMouseEntered
        Font f = Exit_button.getFont();
        Exit_button.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
    }//GEN-LAST:event_Exit_buttonMouseEntered

    private void Exit_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_buttonMouseExited
        Font f = Exit_button.getFont();
        Exit_button.setFont(f.deriveFont(f.getStyle() & ~Font.BOLD));
    }//GEN-LAST:event_Exit_buttonMouseExited

    private void Exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_buttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_Exit_buttonMouseClicked

    private void LambdaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LambdaMouseEntered
        // TODO add your handling code here:
        Lambda.setForeground(Color.white);
    }//GEN-LAST:event_LambdaMouseEntered

    private void LambdaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LambdaMouseExited
        // TODO add your handling code here:
        Lambda.setForeground(new java.awt.Color(244, 169, 80));
    }//GEN-LAST:event_LambdaMouseExited

    private void Check_BalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_BalanceMouseEntered
        // TODO add your handling code here:
        Border border = new LineBorder(Color.white, 5, true);
        Check_Balance.setBorder(border);
        Check_Balance.setForeground(Color.white);
        Check_Balance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_debt_20px_3.png")));  
    }//GEN-LAST:event_Check_BalanceMouseEntered

    private void Check_BalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_BalanceMouseExited
        // TODO add your handling code here:
        
        Check_Balance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 169, 80), 5));
        Check_Balance.setForeground(new java.awt.Color(244, 169, 80));
        Check_Balance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_debt_20px.png"))); 
    }//GEN-LAST:event_Check_BalanceMouseExited

    private void Add_DebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_DebtMouseEntered
        // TODO add your handling code here:
        
        Border border = new LineBorder(Color.white, 5, true);
        Add_Debt.setBorder(border);
        Add_Debt.setForeground(Color.white);
        Add_Debt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_plus_20px_2.png")));  
    }//GEN-LAST:event_Add_DebtMouseEntered

    private void Add_DebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_DebtMouseExited
        // TODO add your handling code here:
        Add_Debt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 169, 80), 5));
        Add_Debt.setForeground(new java.awt.Color(244, 169, 80));
        Add_Debt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_plus_20px.png"))); 
    }//GEN-LAST:event_Add_DebtMouseExited

    private void Pay_DebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pay_DebtMouseEntered
        // TODO add your handling code here:
        Border border = new LineBorder(Color.white, 5, true);
        Pay_Debt.setBorder(border);
        Pay_Debt.setForeground(Color.white);
        Pay_Debt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_minus_20px_1.png")));  
    }//GEN-LAST:event_Pay_DebtMouseEntered

    private void Pay_DebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pay_DebtMouseExited
        // TODO add your handling code here:
        Pay_Debt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 169, 80), 5));
        Pay_Debt.setForeground(new java.awt.Color(244, 169, 80));
        Pay_Debt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_minus_20px_2.png"))); 
    }//GEN-LAST:event_Pay_DebtMouseExited

    private void LambdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LambdaMouseClicked
        // TODO add your handling code here:
        LAMBDACard_window openLAMBDA = new LAMBDACard_window (username, password);
        openLAMBDA.setLocationRelativeTo(this);
        openLAMBDA.setVisible(true);
    }//GEN-LAST:event_LambdaMouseClicked

    private void Check_BalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_BalanceMouseClicked
        // TODO add your handling code here:
        BalanceCredit_window openBalCred = new BalanceCredit_window (username, password);
        openBalCred.setLocationRelativeTo(this);
        openBalCred.setVisible(true);
        
    }//GEN-LAST:event_Check_BalanceMouseClicked

    private void Pay_DebtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pay_DebtMouseClicked
        // TODO add your handling code here:
        PayDebt_window openPayDebt = new PayDebt_window (username, password);
        openPayDebt.setLocationRelativeTo(this);
        openPayDebt.setVisible(true);
    }//GEN-LAST:event_Pay_DebtMouseClicked

    private void Add_DebtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_DebtMouseClicked
        // TODO add your handling code here:
        AddDebt_window openAddDebt = new AddDebt_window (username, password);
        openAddDebt.setLocationRelativeTo(this);
        openAddDebt.setVisible(true);
    }//GEN-LAST:event_Add_DebtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Card_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Card_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Card_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Card_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card_window(username, password).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Debt;
    private javax.swing.JLabel Check_Balance;
    private javax.swing.JLabel Exit_button;
    private javax.swing.JLabel Lambda;
    private javax.swing.JLabel Pay_Debt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
