package bankproject;

/**
 * @author A.A. Yapan
 */
public class Client_homepage extends javax.swing.JFrame {
    
    private static String username;
    private static String password;
    
    public Client_homepage(String x, String y) {
        super("Lambda Home Page");
        username = x;
        password = y;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Check_Balance_Panel = new javax.swing.JPanel();
        Check_Balance_icon = new javax.swing.JLabel();
        Check_balance_text = new javax.swing.JLabel();
        Settings_Panel = new javax.swing.JPanel();
        Settings_icon = new javax.swing.JLabel();
        Settings_text = new javax.swing.JLabel();
        Deposit_Panel = new javax.swing.JPanel();
        Deposit_icon = new javax.swing.JLabel();
        Deposit_text = new javax.swing.JLabel();
        Credit_Card_Panel = new javax.swing.JPanel();
        Credit_card_icon = new javax.swing.JLabel();
        credit_card_text = new javax.swing.JLabel();
        Profile_Panel = new javax.swing.JPanel();
        Profile_icon = new javax.swing.JLabel();
        Profile_text = new javax.swing.JLabel();
        Withdraw_Panel = new javax.swing.JPanel();
        withdraw_icon = new javax.swing.JLabel();
        Withdraw_text = new javax.swing.JLabel();
        Lambda_Loans_Icon = new javax.swing.JLabel();
        Lambda_text = new javax.swing.JLabel();
        Saying_text = new javax.swing.JLabel();

        jPanel5.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel5.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(244, 169, 80));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 33), 2, true));

        jPanel4.setBackground(new java.awt.Color(22, 27, 33));

        Check_Balance_Panel.setBackground(new java.awt.Color(22, 27, 33));
        Check_Balance_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 169, 80), 1, true));
        Check_Balance_Panel.setMinimumSize(new java.awt.Dimension(60, 60));
        Check_Balance_Panel.setPreferredSize(new java.awt.Dimension(80, 80));
        Check_Balance_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check_Balance_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Check_Balance_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Check_Balance_PanelMouseExited(evt);
            }
        });

        Check_Balance_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_money_40px.png"))); // NOI18N

        Check_balance_text.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Check_balance_text.setForeground(new java.awt.Color(240, 240, 240));
        Check_balance_text.setText(" BALANCE");

        javax.swing.GroupLayout Check_Balance_PanelLayout = new javax.swing.GroupLayout(Check_Balance_Panel);
        Check_Balance_Panel.setLayout(Check_Balance_PanelLayout);
        Check_Balance_PanelLayout.setHorizontalGroup(
            Check_Balance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check_Balance_PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Check_Balance_icon)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(Check_Balance_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Check_balance_text, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        Check_Balance_PanelLayout.setVerticalGroup(
            Check_Balance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check_Balance_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Check_Balance_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Check_balance_text)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Settings_Panel.setBackground(new java.awt.Color(22, 27, 33));
        Settings_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 169, 80), 1, true));
        Settings_Panel.setMinimumSize(new java.awt.Dimension(60, 60));
        Settings_Panel.setPreferredSize(new java.awt.Dimension(80, 80));
        Settings_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Settings_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Settings_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Settings_PanelMouseExited(evt);
            }
        });

        Settings_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_settings_40px.png"))); // NOI18N
        Settings_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Settings_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Settings_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Settings_iconMouseExited(evt);
            }
        });

        Settings_text.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        Settings_text.setForeground(new java.awt.Color(240, 240, 240));
        Settings_text.setText("SETTINGS");

        javax.swing.GroupLayout Settings_PanelLayout = new javax.swing.GroupLayout(Settings_Panel);
        Settings_Panel.setLayout(Settings_PanelLayout);
        Settings_PanelLayout.setHorizontalGroup(
            Settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Settings_PanelLayout.createSequentialGroup()
                .addGroup(Settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Settings_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Settings_icon))
                    .addGroup(Settings_PanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Settings_text)))
                .addGap(14, 14, 14))
        );
        Settings_PanelLayout.setVerticalGroup(
            Settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Settings_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Settings_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Settings_text)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Deposit_Panel.setBackground(new java.awt.Color(22, 27, 33));
        Deposit_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 169, 80), 1, true));
        Deposit_Panel.setMinimumSize(new java.awt.Dimension(60, 60));
        Deposit_Panel.setPreferredSize(new java.awt.Dimension(80, 80));
        Deposit_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Deposit_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Deposit_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Deposit_PanelMouseExited(evt);
            }
        });

        Deposit_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_deposit_40px.png"))); // NOI18N

        Deposit_text.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        Deposit_text.setForeground(new java.awt.Color(240, 240, 240));
        Deposit_text.setText(" DEPOSIT");

        javax.swing.GroupLayout Deposit_PanelLayout = new javax.swing.GroupLayout(Deposit_Panel);
        Deposit_Panel.setLayout(Deposit_PanelLayout);
        Deposit_PanelLayout.setHorizontalGroup(
            Deposit_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Deposit_PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Deposit_icon)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(Deposit_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Deposit_text, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        Deposit_PanelLayout.setVerticalGroup(
            Deposit_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Deposit_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Deposit_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deposit_text)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Credit_Card_Panel.setBackground(new java.awt.Color(22, 27, 33));
        Credit_Card_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 169, 80), 1, true));
        Credit_Card_Panel.setMinimumSize(new java.awt.Dimension(60, 60));
        Credit_Card_Panel.setPreferredSize(new java.awt.Dimension(80, 80));
        Credit_Card_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Credit_Card_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Credit_Card_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Credit_Card_PanelMouseExited(evt);
            }
        });

        Credit_card_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_debit_card_40px.png"))); // NOI18N

        credit_card_text.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        credit_card_text.setForeground(new java.awt.Color(240, 240, 240));
        credit_card_text.setText("  CARD");

        javax.swing.GroupLayout Credit_Card_PanelLayout = new javax.swing.GroupLayout(Credit_Card_Panel);
        Credit_Card_Panel.setLayout(Credit_Card_PanelLayout);
        Credit_Card_PanelLayout.setHorizontalGroup(
            Credit_Card_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Credit_Card_PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Credit_card_icon)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Credit_Card_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(credit_card_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Credit_Card_PanelLayout.setVerticalGroup(
            Credit_Card_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Credit_Card_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Credit_card_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(credit_card_text)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Profile_Panel.setBackground(new java.awt.Color(22, 27, 33));
        Profile_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 169, 80), 1, true));
        Profile_Panel.setMinimumSize(new java.awt.Dimension(60, 60));
        Profile_Panel.setPreferredSize(new java.awt.Dimension(80, 80));
        Profile_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Profile_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Profile_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Profile_PanelMouseExited(evt);
            }
        });

        Profile_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_profile_40px.png"))); // NOI18N

        Profile_text.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Profile_text.setForeground(new java.awt.Color(240, 240, 240));
        Profile_text.setText(" PROFILE");

        javax.swing.GroupLayout Profile_PanelLayout = new javax.swing.GroupLayout(Profile_Panel);
        Profile_Panel.setLayout(Profile_PanelLayout);
        Profile_PanelLayout.setHorizontalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Profile_icon)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Profile_text, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        Profile_PanelLayout.setVerticalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Profile_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Profile_text)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Withdraw_Panel.setBackground(new java.awt.Color(22, 27, 33));
        Withdraw_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 169, 80), 1, true));
        Withdraw_Panel.setMinimumSize(new java.awt.Dimension(60, 60));
        Withdraw_Panel.setPreferredSize(new java.awt.Dimension(80, 80));
        Withdraw_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Withdraw_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Withdraw_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Withdraw_PanelMouseExited(evt);
            }
        });

        withdraw_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_withdrawal_40px.png"))); // NOI18N

        Withdraw_text.setFont(new java.awt.Font("SimSun-ExtB", 1, 13)); // NOI18N
        Withdraw_text.setForeground(new java.awt.Color(240, 240, 240));
        Withdraw_text.setText("WITHDRAW");

        javax.swing.GroupLayout Withdraw_PanelLayout = new javax.swing.GroupLayout(Withdraw_Panel);
        Withdraw_Panel.setLayout(Withdraw_PanelLayout);
        Withdraw_PanelLayout.setHorizontalGroup(
            Withdraw_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Withdraw_PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(withdraw_icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Withdraw_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Withdraw_text, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );
        Withdraw_PanelLayout.setVerticalGroup(
            Withdraw_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Withdraw_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdraw_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Withdraw_text)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Lambda_Loans_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_hand_holding_dollar_90px.png"))); // NOI18N

        Lambda_text.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Lambda_text.setForeground(new java.awt.Color(244, 169, 80));
        Lambda_text.setText("LAMBDA LOANS");
        Lambda_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lambda_textMouseClicked(evt);
            }
        });

        Saying_text.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        Saying_text.setForeground(new java.awt.Color(240, 240, 240));
        Saying_text.setText("OUGHT TO SECURE YOUR MONEY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Profile_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Withdraw_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Credit_Card_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Deposit_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Check_Balance_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Settings_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lambda_Loans_Icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Saying_text)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Lambda_text)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lambda_Loans_Icon))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Lambda_text)
                        .addGap(0, 0, 0)
                        .addComponent(Saying_text)))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Check_Balance_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profile_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deposit_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Withdraw_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Credit_Card_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Settings_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lambda_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lambda_textMouseClicked
        
    }//GEN-LAST:event_Lambda_textMouseClicked

    private void Settings_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_PanelMouseEntered
        Settings_Panel.setBackground(new java.awt.Color(244,169,80));
        Settings_text.setForeground(new java.awt.Color(22,27,33));
        Settings_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_settings_40px_2.png")));
    }//GEN-LAST:event_Settings_PanelMouseEntered

    private void Settings_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_PanelMouseExited
        Settings_Panel.setBackground(new java.awt.Color(22,27,33));
        Settings_text.setForeground(new java.awt.Color(240,240,240));
        Settings_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_settings_40px.png")));
    }//GEN-LAST:event_Settings_PanelMouseExited

    private void Credit_Card_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Credit_Card_PanelMouseEntered
        Credit_Card_Panel.setBackground(new java.awt.Color(244,169,80));
        credit_card_text.setForeground(new java.awt.Color(22,27,33));
        Credit_card_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_debit_card_40px_1.png")));
    }//GEN-LAST:event_Credit_Card_PanelMouseEntered

    private void Credit_Card_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Credit_Card_PanelMouseExited
        Credit_Card_Panel.setBackground(new java.awt.Color(22,27,33));
        credit_card_text.setForeground(new java.awt.Color(240,240,240));
        Credit_card_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_debit_card_40px.png")));
    }//GEN-LAST:event_Credit_Card_PanelMouseExited

    private void Withdraw_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Withdraw_PanelMouseEntered
        Withdraw_Panel.setBackground(new java.awt.Color(244,169,80));
        Withdraw_text.setForeground(new java.awt.Color(22,27,33));
        withdraw_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_withdrawal_40px_1.png")));
    }//GEN-LAST:event_Withdraw_PanelMouseEntered

    private void Withdraw_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Withdraw_PanelMouseExited
        Withdraw_Panel.setBackground(new java.awt.Color(22,27,33));
        Withdraw_text.setForeground(new java.awt.Color(240,240,240));
        withdraw_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_withdrawal_40px.png")));
    }//GEN-LAST:event_Withdraw_PanelMouseExited

    private void Deposit_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deposit_PanelMouseEntered
        Deposit_Panel.setBackground(new java.awt.Color(244,169,80));
        Deposit_text.setForeground(new java.awt.Color(22,27,33));
        Deposit_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_deposit_40px_1.png")));
    }//GEN-LAST:event_Deposit_PanelMouseEntered

    private void Deposit_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deposit_PanelMouseExited
        Deposit_Panel.setBackground(new java.awt.Color(22,27,33));
        Deposit_text.setForeground(new java.awt.Color(240,240,240));
        Deposit_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_deposit_40px.png")));
    }//GEN-LAST:event_Deposit_PanelMouseExited

    private void Profile_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_PanelMouseEntered
        Profile_Panel.setBackground(new java.awt.Color(244,169,80));
        Profile_text.setForeground(new java.awt.Color(22,27,33));
        Profile_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_profile_40px_1.png")));
    }//GEN-LAST:event_Profile_PanelMouseEntered

    private void Profile_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_PanelMouseExited
        Profile_Panel.setBackground(new java.awt.Color(22,27,33));
        Profile_text.setForeground(new java.awt.Color(240,240,240));
        Profile_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_profile_40px.png")));
    }//GEN-LAST:event_Profile_PanelMouseExited

    private void Check_Balance_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_Balance_PanelMouseEntered
        Check_Balance_Panel.setBackground(new java.awt.Color(244,169,80));
        Check_balance_text.setForeground(new java.awt.Color(22,27,33));
        Check_Balance_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_money_40px_1.png")));
    }//GEN-LAST:event_Check_Balance_PanelMouseEntered

    private void Check_Balance_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_Balance_PanelMouseExited
        Check_Balance_Panel.setBackground(new java.awt.Color(22,27,33));
        Check_balance_text.setForeground(new java.awt.Color(240,240,240));
        Check_Balance_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_money_40px.png")));
    }//GEN-LAST:event_Check_Balance_PanelMouseExited

    private void Settings_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_iconMouseClicked
        Setting_Window openSetting = new Setting_Window(username, password);
        openSetting.setVisible(true);
        openSetting.setLocationRelativeTo(this);
    }//GEN-LAST:event_Settings_iconMouseClicked

    private void Settings_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_PanelMouseClicked
        Setting_Window openSetting = new Setting_Window(username, password);
        openSetting.setVisible(true);
        openSetting.setLocationRelativeTo(this);
    }//GEN-LAST:event_Settings_PanelMouseClicked

    private void Settings_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_iconMouseEntered
        Settings_Panel.setBackground(new java.awt.Color(244,169,80));
        Settings_text.setForeground(new java.awt.Color(22,27,33));
        Settings_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_settings_40px_2.png")));
    }//GEN-LAST:event_Settings_iconMouseEntered

    private void Settings_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_iconMouseExited
        Settings_Panel.setBackground(new java.awt.Color(22,27,33));
        Settings_text.setForeground(new java.awt.Color(240,240,240));
        Settings_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_settings_40px.png")));
    }//GEN-LAST:event_Settings_iconMouseExited

    private void Profile_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_PanelMouseClicked
        Profile_window newProfileWindow = new Profile_window(username, password);
        newProfileWindow.setLocationRelativeTo(this);
        newProfileWindow.setVisible(true);
    }//GEN-LAST:event_Profile_PanelMouseClicked

    private void Check_Balance_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_Balance_PanelMouseClicked
        Balance_window newBalanceWindow = new Balance_window(username, password);
        newBalanceWindow.setLocationRelativeTo(this);
        newBalanceWindow.setVisible(true);
    }//GEN-LAST:event_Check_Balance_PanelMouseClicked

    private void Withdraw_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Withdraw_PanelMouseClicked
        Withdraw_window newWithdrawWindow = new Withdraw_window(username, password);
        newWithdrawWindow.setLocationRelativeTo(this);
        newWithdrawWindow.setVisible(true);
    }//GEN-LAST:event_Withdraw_PanelMouseClicked

    private void Deposit_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deposit_PanelMouseClicked
        Deposit_window newDepositWindow = new Deposit_window(username, password);
        newDepositWindow.setLocationRelativeTo(this);
        newDepositWindow.setVisible(true);
    }//GEN-LAST:event_Deposit_PanelMouseClicked

    private void Credit_Card_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Credit_Card_PanelMouseClicked
        Card_window newCardWindow = new Card_window(username, password);
        newCardWindow.setLocationRelativeTo(this);
        newCardWindow.setVisible(true);
    }//GEN-LAST:event_Credit_Card_PanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_homepage(username, password).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Check_Balance_Panel;
    private javax.swing.JLabel Check_Balance_icon;
    private javax.swing.JLabel Check_balance_text;
    private javax.swing.JPanel Credit_Card_Panel;
    private javax.swing.JLabel Credit_card_icon;
    private javax.swing.JPanel Deposit_Panel;
    private javax.swing.JLabel Deposit_icon;
    private javax.swing.JLabel Deposit_text;
    private javax.swing.JLabel Lambda_Loans_Icon;
    private javax.swing.JLabel Lambda_text;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JLabel Profile_icon;
    private javax.swing.JLabel Profile_text;
    private javax.swing.JLabel Saying_text;
    private javax.swing.JPanel Settings_Panel;
    private javax.swing.JLabel Settings_icon;
    private javax.swing.JLabel Settings_text;
    private javax.swing.JPanel Withdraw_Panel;
    private javax.swing.JLabel Withdraw_text;
    private javax.swing.JLabel credit_card_text;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel withdraw_icon;
    // End of variables declaration//GEN-END:variables
}
