
package bankproject;

import java.sql.*;

/**
 * @author A.A. Yapan
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    public Login_Form() {
        super("Login to Lambda Loans");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        Username_textfield = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Password_field = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        Username_icon = new javax.swing.JLabel();
        Password_icon = new javax.swing.JLabel();
        minimize_button = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        exit_button = new javax.swing.JLabel();
        Login_panel = new javax.swing.JPanel();
        Login_text = new javax.swing.JLabel();
        Register_panel = new javax.swing.JPanel();
        Register_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(788, 410));

        jPanel2.setBackground(new java.awt.Color(22, 27, 33));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_hand_holding_dollar_120px_1.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 169, 80));
        jLabel7.setText("LAMBDA LOANS");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("OUGHT TO SECURE YOUR MONEY");

        jSeparator3.setForeground(new java.awt.Color(244, 169, 80));
        jSeparator3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 169, 80), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jPanel3.setBackground(new java.awt.Color(244, 169, 80));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 33), 2, true));
        jPanel3.setForeground(new java.awt.Color(22, 27, 33));
        jPanel3.setPreferredSize(new java.awt.Dimension(468, 410));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        Username_textfield.setBackground(new java.awt.Color(244, 169, 80));
        Username_textfield.setForeground(new java.awt.Color(51, 51, 51));
        Username_textfield.setText("Username");
        Username_textfield.setBorder(null);
        Username_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Username_textfieldMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(22, 27, 33));

        Password_field.setBackground(new java.awt.Color(244, 169, 80));
        Password_field.setForeground(new java.awt.Color(51, 51, 51));
        Password_field.setText("yourpassword");
        Password_field.setBorder(null);
        Password_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Password_fieldMouseClicked(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(22, 27, 33));

        Username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_group_30px.png"))); // NOI18N

        Password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_keepass_30px.png"))); // NOI18N

        minimize_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize_button.setForeground(new java.awt.Color(29, 27, 27));
        minimize_button.setText("  _");
        minimize_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseExited(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(22, 27, 33));
        jSeparator4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 33), 1, true));

        exit_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit_button.setForeground(new java.awt.Color(22, 27, 33));
        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_delete_30px_3.png"))); // NOI18N
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_buttonMouseExited(evt);
            }
        });

        Login_panel.setBackground(new java.awt.Color(244, 169, 80));
        Login_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_panelMouseEntered(evt);
            }
        });

        Login_text.setForeground(new java.awt.Color(22, 27, 33));
        Login_text.setText("      Login");
        Login_text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 33), 1, true));
        Login_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_textMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Login_panelLayout = new javax.swing.GroupLayout(Login_panel);
        Login_panel.setLayout(Login_panelLayout);
        Login_panelLayout.setHorizontalGroup(
            Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Login_text, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Login_panelLayout.setVerticalGroup(
            Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login_panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Login_text, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Register_panel.setBackground(new java.awt.Color(244, 169, 80));
        Register_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_panelMouseEntered(evt);
            }
        });

        Register_text.setForeground(new java.awt.Color(22, 27, 33));
        Register_text.setText("    Register");
        Register_text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 33), 1, true));
        Register_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Register_textMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Register_panelLayout = new javax.swing.GroupLayout(Register_panel);
        Register_panel.setLayout(Register_panelLayout);
        Register_panelLayout.setHorizontalGroup(
            Register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_panelLayout.createSequentialGroup()
                .addComponent(Register_text, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Register_panelLayout.setVerticalGroup(
            Register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Register_text, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Register_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Password_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Username_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Password_field)
                                    .addComponent(jSeparator2)
                                    .addComponent(Username_textfield)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize_button)
                    .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Username_icon))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Register_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_textfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_textfieldMouseClicked
        // Username textfield
        Username_textfield.setText("");
        String strEmpt = new String(Password_field.getPassword());
        if(strEmpt.equalsIgnoreCase("")){
            Password_field.setText("yourpassword");
        }
    }//GEN-LAST:event_Username_textfieldMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        
        if(Username_textfield.getText().equalsIgnoreCase("")){
            Username_textfield.setText("Username");
        }
        String strEmpt = new String(Password_field.getPassword());
        if(strEmpt.equalsIgnoreCase("")){
            Password_field.setText("yourpassword");
        }
         
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        
        if(Username_textfield.getText().equalsIgnoreCase("")){
            Username_textfield.setText("Username");
        }
        String strEmpt = new String(Password_field.getPassword());
        if(strEmpt.equalsIgnoreCase("")){
            Password_field.setText("yourpassword");
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(Username_textfield.getText().equalsIgnoreCase("")){
            Username_textfield.setText("Username");
        }
        String strEmpt = new String(Password_field.getPassword());
        if(strEmpt.equalsIgnoreCase("")){
            Password_field.setText("yourpassword");
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if(Username_textfield.getText().equalsIgnoreCase("")){
            Username_textfield.setText("Username");
        }
        String strEmpt = new String(Password_field.getPassword());
        if(strEmpt.equalsIgnoreCase("")){
            Password_field.setText("yourpassword");
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void Password_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_fieldMouseClicked
        Password_field.setText("");
        if(Username_textfield.getText().equalsIgnoreCase("")){
            Username_textfield.setText("Username");
        }
    }//GEN-LAST:event_Password_fieldMouseClicked

    private void minimize_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseClicked
        // MINIMIZE BUTTON
        this.setExtendedState(Login_Form.ICONIFIED);
    }//GEN-LAST:event_minimize_buttonMouseClicked

    private void Register_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_textMouseClicked
        // REGISTER BUTTON
        
        Admin mainAdmin = new Admin("Admin",21);
        
        String strEmpt = new String(Password_field.getPassword());
        if(((Username_textfield.getText().equalsIgnoreCase("")) || (Username_textfield.getText().equalsIgnoreCase("Username"))) && ((strEmpt.equalsIgnoreCase("")) || strEmpt.equalsIgnoreCase("yourpassword"))){
  
            Enter_admin_account OpenPrompt = new Enter_admin_account();
            OpenPrompt.setLocationRelativeTo(this);
            OpenPrompt.setVisible(true);
        }
        
        if(Username_textfield.getText().equalsIgnoreCase("")){
            Username_textfield.setText("Username");
        }
        
        if(strEmpt.equalsIgnoreCase("")){
            Password_field.setText("yourpassword");
        }
        
        boolean ifAdmin = false;
        if(Username_textfield.getText().equals(mainAdmin.getName()) && strEmpt.equals(mainAdmin.adminPassword)){
            Register_Form OpenRegister = new Register_Form();
            OpenRegister.setLocationRelativeTo(this);
            OpenRegister.setVisible(true);
            ifAdmin = true;
        }else if (!(strEmpt.equals("yourpassword")) && !(Username_textfield.getText().equals("Username")) && !(ifAdmin) ){
            Enter_admin_account OpenPrompt = new Enter_admin_account();
            OpenPrompt.setLocationRelativeTo(this);
            OpenPrompt.setVisible(true);
        }
        
        
    }//GEN-LAST:event_Register_textMouseClicked

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        // EXIT BUTTON
        this.dispose();
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void Login_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_panelMouseEntered
        
        Login_text.setForeground(new java.awt.Color(244,169,80));
        Login_panel.setBackground(new java.awt.Color(22,27,33));
    }//GEN-LAST:event_Login_panelMouseEntered

    private void Register_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_panelMouseEntered
        
        Register_text.setForeground(new java.awt.Color(244,169,80));
        Register_panel.setBackground(new java.awt.Color(22,27,33));
    }//GEN-LAST:event_Register_panelMouseEntered

    private void Register_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_textMouseEntered
        
        Register_text.setForeground(new java.awt.Color(244,169,80));
        Register_panel.setBackground(new java.awt.Color(22,27,33));
    }//GEN-LAST:event_Register_textMouseEntered

    private void Login_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_textMouseEntered
        
        Login_text.setForeground(new java.awt.Color(244,169,80));
        Login_panel.setBackground(new java.awt.Color(22,27,33));
    }//GEN-LAST:event_Login_textMouseEntered

    private void Login_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_textMouseExited
        
        Login_panel.setBackground(new java.awt.Color(244,169,80));
        Login_text.setForeground(new java.awt.Color(22,27,33));
    }//GEN-LAST:event_Login_textMouseExited

    private void Register_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_textMouseExited
        Register_panel.setBackground(new java.awt.Color(244,169,80));
        Register_text.setForeground(new java.awt.Color(22,27,33));
    }//GEN-LAST:event_Register_textMouseExited

    private void Login_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_textMouseClicked
        boolean no_input = false;
        String strEmpt = new String(Password_field.getPassword());
        String username;
        String password;
        
        
        
        try {
           
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clientdb", "root", "admin1");
            Statement st = con.createStatement();
        
        if(((Username_textfield.getText().equalsIgnoreCase("")) || (Username_textfield.getText().equalsIgnoreCase("Username"))) && ((strEmpt.equalsIgnoreCase("")) || strEmpt.equalsIgnoreCase("yourpassword"))){
            no_input = true;
            Enter_account OpenPrompt = new Enter_account();
            OpenPrompt.setLocationRelativeTo(this);
            OpenPrompt.setVisible(true);
        }      
        if(Username_textfield.getText().equalsIgnoreCase("")){
            Username_textfield.setText("Username");
        }
        
        if(strEmpt.equalsIgnoreCase("")){
            Password_field.setText("yourpassword");
        }
        
        if (checkAccount(Username_textfield.getText(), strEmpt)){
            
            username = Username_textfield.getText();
            password = strEmpt;
            After_login after_login = new After_login(username, password);
            after_login.setLocationRelativeTo(this);
            after_login.setVisible(true);
            this.dispose();
        }else{
            if(!no_input){
                Invalid_account invalidAccount = new Invalid_account();
                invalidAccount.setVisible(true);
                invalidAccount.setLocationRelativeTo(this);
            }   
        }
        }
        catch (SQLException ex) {
           ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_Login_textMouseClicked

    
    public boolean checkAccount (String x, String y){
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clientdb", "root", "admin1");
                Statement st = con.createStatement();

            String hold;

            ResultSet rs = st.executeQuery("SELECT Password FROM clientinfo WHERE Name = " + "'" + x +"'");

            if (rs.next()){
                hold = rs.getString("Password");
            }
            else {
                return false;
            }
            if (y.equals(hold)){
                return true;
            }
        
        } catch (SQLException e){
            e.printStackTrace();
        }
        return false;
        
    }
    
    private void exit_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseEntered
        
        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_delete_30px_4.png")));
    }//GEN-LAST:event_exit_buttonMouseEntered

    private void exit_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseExited
        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_delete_30px_3.png")));
    }//GEN-LAST:event_exit_buttonMouseExited

    private void minimize_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseEntered
        minimize_button.setForeground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_minimize_buttonMouseEntered

    private void minimize_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseExited
        minimize_button.setForeground(new java.awt.Color(29,27,27));
    }//GEN-LAST:event_minimize_buttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_panel;
    private javax.swing.JLabel Login_text;
    private javax.swing.JPasswordField Password_field;
    private javax.swing.JLabel Password_icon;
    private javax.swing.JPanel Register_panel;
    private javax.swing.JLabel Register_text;
    private javax.swing.JLabel Username_icon;
    private javax.swing.JTextField Username_textfield;
    private javax.swing.JLabel exit_button;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel minimize_button;
    // End of variables declaration//GEN-END:variables
}
