package bankproject;

import java.awt.Font;

/**
 * @author A.A. Yapan
 */
public class Setting_Window extends javax.swing.JFrame {

    /**
     * Creates new form Setting_Window
     */
    private static String username;
    private static String password;
    public Setting_Window(String x, String y) {
        username = x;
        password = y;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Line1 = new javax.swing.JLabel();
        Line2 = new javax.swing.JLabel();
        Line3 = new javax.swing.JLabel();
        Line4 = new javax.swing.JLabel();
        Line5 = new javax.swing.JLabel();
        Line6 = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JLabel();
        About_icon = new javax.swing.JLabel();
        Logout_icon = new javax.swing.JLabel();
        change_pass_icon = new javax.swing.JLabel();
        Close_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(244, 169, 80));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 27, 33), 2, true));

        jPanel2.setBackground(new java.awt.Color(22, 27, 33));

        Line1.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Line1.setForeground(new java.awt.Color(240, 240, 240));

        Line2.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Line2.setForeground(new java.awt.Color(240, 240, 240));

        Line3.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Line3.setForeground(new java.awt.Color(240, 240, 240));

        Line4.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Line4.setForeground(new java.awt.Color(240, 240, 240));

        Line5.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Line5.setForeground(new java.awt.Color(240, 240, 240));

        Line6.setFont(new java.awt.Font("SimSun-ExtB", 1, 11)); // NOI18N
        Line6.setForeground(new java.awt.Color(240, 240, 240));

        Exit_Button.setFont(new java.awt.Font("SimSun-ExtB", 0, 11)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(240, 240, 240));
        Exit_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_ButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Line2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Line3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Line5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Line6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(Exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Line1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        About_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_about_30px.png"))); // NOI18N
        About_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                About_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                About_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                About_iconMouseExited(evt);
            }
        });

        Logout_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_exit_32px_1.png"))); // NOI18N
        Logout_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_iconMouseExited(evt);
            }
        });

        change_pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_password_reset_30px_1.png"))); // NOI18N
        change_pass_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_pass_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                change_pass_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                change_pass_iconMouseExited(evt);
            }
        });

        Close_button.setFont(new java.awt.Font("SimSun-ExtB", 0, 11)); // NOI18N
        Close_button.setForeground(new java.awt.Color(0, 0, 0));
        Close_button.setText("Close");
        Close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_buttonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(change_pass_icon)
                            .addComponent(Logout_icon))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(About_icon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Close_button, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(About_icon)
                        .addGap(46, 46, 46)
                        .addComponent(change_pass_icon)
                        .addGap(34, 34, 34)
                        .addComponent(Logout_icon)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_iconMouseEntered
        Logout_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_exit_32px.png")));
    }//GEN-LAST:event_Logout_iconMouseEntered

    private void Logout_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_iconMouseExited
        Logout_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_exit_32px_1.png")));
    }//GEN-LAST:event_Logout_iconMouseExited

    private void change_pass_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pass_iconMouseEntered
        change_pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_password_reset_30px.png")));
    }//GEN-LAST:event_change_pass_iconMouseEntered

    private void change_pass_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pass_iconMouseExited
        change_pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_password_reset_30px_1.png")));
    }//GEN-LAST:event_change_pass_iconMouseExited

    private void About_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_iconMouseEntered
        About_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_about_30px_2.png")));
    }//GEN-LAST:event_About_iconMouseEntered

    private void About_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_iconMouseExited
        About_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankproject/Resources/icons8_about_30px.png")));
    }//GEN-LAST:event_About_iconMouseExited

    private void About_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_iconMouseClicked
        clickable_exit_button = false;
        clickable_change_pass_button = false;
        Line1.setText("ABOUT");
        Line2.setText("Version: Alpha Test");
        Line3.setText("Creator: 'LAMBDA'");
        Line4.setText("   Product Manager: Dave Amiana");
        Line5.setText("   Back-End Developer: Kevin Cortes");
        Line6.setText("   Front-End Developer: Akio Yapan");
        Exit_Button.setText("");
    }//GEN-LAST:event_About_iconMouseClicked
    boolean clickable_exit_button = false;
    boolean clickable_change_pass_button = false;
    private void Logout_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_iconMouseClicked
        clickable_exit_button = true;
        clickable_change_pass_button = false;
        Line1.setText("LOGOUT & EXIT");
        Line2.setText("Do you want to exit?");
        Line3.setText("");
        Line4.setText("");
        Line5.setText("");
        Line6.setText("");
        Exit_Button.setText("YES");
    }//GEN-LAST:event_Logout_iconMouseClicked

    private void Exit_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_ButtonMouseEntered
        if(clickable_exit_button || clickable_change_pass_button){
           Font f = Exit_Button.getFont();
            Exit_Button.setFont(f.deriveFont(f.getStyle() | Font.BOLD)); 
        }
        
    }//GEN-LAST:event_Exit_ButtonMouseEntered

    private void Exit_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_ButtonMouseExited
        if(clickable_exit_button || clickable_change_pass_button){
            Font f = Exit_Button.getFont();
            Exit_Button.setFont(f.deriveFont(f.getStyle() & ~Font.BOLD));
        }
    }//GEN-LAST:event_Exit_ButtonMouseExited

    private void Exit_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_ButtonMouseClicked
        if(clickable_exit_button){
            System.exit(0);
        }else if(clickable_change_pass_button){
            Change_pass_window newChangePass = new Change_pass_window(username, password);
            newChangePass.setLocationRelativeTo(this);
            newChangePass.setVisible(true);
        }
    }//GEN-LAST:event_Exit_ButtonMouseClicked

    private void change_pass_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pass_iconMouseClicked
        clickable_exit_button = false;
        clickable_change_pass_button = true;
        Line1.setText("CHANGE PASSWORD");
        Line2.setText("Do you want to change your password?");
        Line3.setText("");
        Line4.setText("");
        Line5.setText("");
        Line6.setText("");
        Exit_Button.setText("YES");
    }//GEN-LAST:event_change_pass_iconMouseClicked

    private void Close_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_buttonMouseEntered
        Font f = Close_button.getFont();
        Close_button.setFont(f.deriveFont(f.getStyle() | Font.BOLD)); 
    }//GEN-LAST:event_Close_buttonMouseEntered

    private void Close_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_buttonMouseExited
        Font f = Close_button.getFont();
        Close_button.setFont(f.deriveFont(f.getStyle() & ~Font.BOLD)); 
    }//GEN-LAST:event_Close_buttonMouseExited

    private void Close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_buttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_Close_buttonMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting_Window(username, password).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About_icon;
    private javax.swing.JLabel Close_button;
    private javax.swing.JLabel Exit_Button;
    private javax.swing.JLabel Line1;
    private javax.swing.JLabel Line2;
    private javax.swing.JLabel Line3;
    private javax.swing.JLabel Line4;
    private javax.swing.JLabel Line5;
    private javax.swing.JLabel Line6;
    private javax.swing.JLabel Logout_icon;
    private javax.swing.JLabel change_pass_icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
